baseURL = "https://pnevmalex.dev/"
# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"
# website title
title = "Pnevmalex"
# language code ["en", "zh-CN", "fr", "pl", ...]
languageCode = "en"
# language name ["English", "简体中文", "Français", "Polski", ...]
languageName = "English"


# default amount of posts in each pages
[pagination]
  pagerSize = 10

# whether to use robots.txt
enableRobotsTXT = false
# whether to use git commit log
enableGitInfo = true
# whether to use emoji code
enableEmoji = false

# ignore some build errors
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# Author config
[author]
  name = "Alexandros Pnevmonidis"
  email = "pnevmalex@protonmail.com"
  link = "https://pnevmalex.dev/"

[params]
  # site default theme ["auto", "light", "dark"]
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  gitRepo = "https://github.com/Pnevmalex/Portfolio"
  # which hash function used for SRI, when empty, no SRI is used
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = ""
  # date format
  dateFormat = "2006-01-02"
  # website title for Open Graph and Twitter Cards
  title = "Pnevmalex"
  # website description for RSS, SEO, Open Graph and Twitter Cards
  description = "Pnevmalex - Blog"
  # website images for Open Graph and Twitter Cards
  images = ["/logo.png"]

  # Header config
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "Pnevmalex"
      # you can add extra information before the name (HTML format is supported), such as icons
      # pre = "<i class='far fa-kiss-wink-heart fa-fw' aria-hidden='true'></i>"
      pre = "<i class='fa-solid fa-terminal fa-fw' aria-hidden='true'></i>"
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # whether to use typeit animation for title name
      typeit = false

  # Footer config
  [params.footer]
    enable = true
    # Custom content (HTML format is supported)
    custom = ""
    # whether to show Hugo and theme info
    hugo = false
    # whether to show copyright info
    copyright = true
    # whether to show the author
    author = true
    # site creation time
    since = 2020
    # ICP info only in China (HTML format is supported)
    icp = ""
    # license info (HTML format is supported)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # Section (all posts) page config
  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # List (category or tag) page config
  [params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # App icon config
  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "Pnevmalex"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = "favicon.svg"
    # Android browser theme color
    themeColor = "#ffffff"
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-11 tile color
    tileColor = "#da532c"

  # Search config
  [params.search]
    enable = false

  # Home page config
  [params.home]
    # amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # URL of avatar shown in home page
      avatarURL = "/images/avatar.png"
      # title shown in home page (HTML format is supported)
      title = "Alexandros Pnevmonidis"
      # subtitle shown in home page (HTML format is supported)
      subtitle = "A Developer in making"
      # whether to use typeit animation for subtitle  
      typeit = true
      # whether to show social links     
      social = true
      # disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = false
  # Social config in home page
  [params.social]
    GitHub = ""
    Linkedin = ""
    Instagram = ""
    Email = ""

  # Page global config
  [params.page]
    # whether to hide a page from home page
    hiddenFromHomePage = false
    # whether to hide a page from search results
    hiddenFromSearch = false
    # whether to enable twemoji
    twemoji = false
    # whether to enable lightgallery
    lightgallery = false
    # whether to enable the ruby extended syntax
    ruby = true
    # whether to enable the fraction extended syntax
    fraction = true
    # whether to enable the fontawesome extended syntax
    fontawesome = true
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = true
    # whether to show the full text content in RSS
    rssFullText = false
    # Table of the contents config
    [params.page.toc]
      # whether to enable the table of the contents
      enable = true
      # whether to keep the static table of the contents in front of the post
      keepStatic = false
      # whether to make the table of the contents in the sidebar automatically collapsed  
      auto = true
    # Code config
    [params.page.code]
      # whether to show the copy button of the code block  
      copy = true
      # the maximum number of lines of displayed code by default     
      maxShownLines = 50
    # KaTeX mathematical formulas config (KaTeX https://katex.org/)    
    [params.page.math]
      enable = false
      # default inline delimiter is $ ... $ and \( ... \)      
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # default block delimiter is $$ ... $$, \[ ... \], \begin{equation} ... \end{equation} and some other functions    
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # KaTeX extension copy_tex    
      copyTex = true
      # KaTeX extension mhchem  
      mhchem = true
    # Mapbox GL JS config (Mapbox GL JS https://docs.mapbox.com/mapbox-gl-js)
    
    
    # Social share links in post page
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true
      Reddit = true
    # Comment config
    [params.page.comment]
      enable = false
      
      # utterances comment config (https://utteranc.es/)
      [params.page.comment.utterances]
        enable = false
        # owner/repo
        repo = ""
        issueTerm = "pathname"
        label = ""
        lightTheme = "github-light"
        darkTheme = "github-dark"
     
    # Page SEO config
    [params.page.seo]
      # image URL
      images = []
      # Publisher info
      [params.page.seo.publisher]
        name = "Alexandros Pnevmonidis"
        logoUrl = "/images/avatar.png"

  # TypeIt config
  [params.typeit]
    # typing speed between each step (measured in milliseconds)
    speed = 100
    # blinking speed of the cursor (measured in milliseconds)
    cursorSpeed = 1000
    # character used for the cursor (HTML format is supported)
    cursorChar = "|"
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    duration = -1

  # Site verification code for Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""

  # # Site SEO config
  # # 网站 SEO 配置
  # [params.seo]
  #   # image URL
  #   # 图片 URL
  #   image = "/images/Apple-Devices-Preview.png"
  #   # thumbnail URL
  #   # 缩略图 URL
  #   thumbnailUrl = "/images/screenshot.png"

  # Analytics config
  [params.analytics]
    enable = false

  # Cookie consent config
  [params.cookieconsent]
    enable = false
  # CDN config for third-party library files
  [params.cdn]
    # CDN data file name, disabled by default
    # ["jsdelivr.yml"]
    # located in "themes/LoveIt/assets/data/cdn/" directory
    # you can store your own data files in the same path under your project:
    # "assets/data/cdn/"
    data = "jsdelivr.yml"

  # Compatibility config

  [params.compatibility]
    # whether to use Polyfill.io to be compatible with older browsers
    
    polyfill = false
    # whether to use object-fit-images to be compatible with older browsers
    
    objectFit = false

# Markup related configuration in Hugo

[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
 
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      
      unsafe = true
  # Table Of Contents settings

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Sitemap config

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks config (https://gohugo.io/content-management/urls/#permalinks)

[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"

# Privacy config (https://gohugo.io/about/hugo-and-gdpr/)

[privacy]
  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files

[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

# Multilingual

[languages]
  [languages.en]
    weight = 1
    languageCode = "en"
    languageName = "English"
    hasCJKLanguage = false
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    [languages.en.menu]
      [[languages.en.menu.main]]
        weight = 1
        identifier = "about"
        pre = ""
        post = ""
        name = "About"
        url = "/about/"
        title = ""
      [[languages.en.menu.main]]
        weight = 2
        identifier = "posts"
        pre = ""
        post = ""
        name = "Posts"
        url = "/posts/"
        title = ""
      [[languages.en.menu.main]]
        weight = 3
        identifier = "projects"
        pre = ""
        post = ""
        name = "Projects"
        url = "/projects/"
        title = ""
      [[languages.en.menu.main]]
        weight = 4
        identifier = "github"
        pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
        post = ""
        name = ""
        url = "https://github.com/Pnevmalex/Portfolio"
        title = "GitHub"
    [languages.en.params]
      [languages.en.params.home]
        rss = 10
        [languages.en.params.home.profile]
          enable = true
          avatarURL = "/images/avatar.png"
          title = "Alexandros Pnevmonidis"
          subtitle = "Everything should be made as simple as possible, but not simpler."
          typeit = true
          social = true
          disclaimer = ""
      [languages.en.params.social]
        GitHub = "Pnevmalex"
        Linkedin = "Pnevmalex"
        Instagram = "Pnevmalex"
        Email = "pnevmalex@protonmail.com"
